---

downloads: "/tmp/ansible-downloads/"

configure_dotfiles: yes
configure_packages: yes
configure_sdkman: yes
configure_zsh: yes
configure_chrome: no
configure_idea: yes
configure_snap_packages: yes
configure_ssh: yes
configure_extra_packages: yes
configure_folders: yes

dotfiles_repo: "https://github.com/GlaIZier/configs"
dotfiles_repo_version: master
dotfiles_repo_local_destination: "~/github/configs-linux-environment"
dotfiles_repo_accept_hostkey: false
dotfiles_files:
  - linux/.bash_profile
  - linux/.bashrc
  - linux/.profile
  - linux/.zprofile
  - linux/.zshrc
  - general/.gitignore
  - general/.gitconfig
dotfiles_home: "~"

# python should be installed manually since it is easy to break current python2 used on the system
packages:
  - bash-completion
  - git
  - openssl
  - wget
  - zsh
  - terminator
  - chromium-browser
  - keepassx
  - copyq
  - vim
  - gnome-tweak-tool
  - gnome-shell-extensions # Put windows - spectacle
  - gnome-shell-extension-system-monitor
  - chrome-gnome-shell
  - snapd


# see the sdkman role https://github.com/Comcast/ansible-sdkman
sdkman_install_packages:
#  - { candidate: java, version: '' }
  - { candidate: java, version: '8.0.212-amzn' }
  - { candidate: java, version: '11.0.3.hs-adpt' }
#  - { candidate: java, version: '11.0.2-open' }
  - { candidate: gradle, version: '' }
  - { candidate: maven, version: '' }


snap_packages:
  - { name: skype, classic: yes }
  - { name: sublime-text, classic: yes }
  - { name: plexmediaserver, classic: no }
#  - {name: intellij-idea-ultimate, classic: yes} # commented by default because i don't want idea to be updated automatically as snap does

intellij_edition: ultimate
intellij_install_dir: /opt/idea-{{ intellij_edition }}-{{ intellij_version }}
intellij_download_dir: {{ downloads }}/idea


# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

zsh_autosuggestions_bind_key: "^U"

ssh_key_name: github_rsa

folders:
  - ~/app
  - ~/github
  - ~/tmp

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []