---
- hosts: localhost

  vars_files:
    - default.config.yml

  pre_tasks:

    - debug: msg="ansible_facts.pkg_mgr = {{ ansible_facts.pkg_mgr }}"

    - include_tasks: tasks/ansible-check.yml

    # update the default.config.yml variables with ones from config.yml if it exists
    - include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

    - include_tasks: tasks/dotfiles.yml
      when: configure_dotfiles | bool
      tags: ['dotfiles']

    - include_tasks: tasks/packages.yml
      become: yes
      when: configure_packages | bool
      tags: ['packages']

  roles:
    # https://github.com/Comcast/ansible-sdkman
    - role: comcast.sdkman
      when: configure_sdkman | bool
      tags: ['sdkman']
    # https://github.com/viasite-ansible/ansible-role-zsh
    - role: viasite-ansible.zsh
      become: yes
      when: configure_zsh | bool
      tags: ['zsh']
    # https://github.com/cmprescott/ansible-role-chrome
    - role: cmprescott.chrome
      become: yes
      when: configure_chrome | bool
      tags: ['chrome']



  tasks:

    - include_tasks: tasks/snap-packages.yml
      become: yes
      when: configure_snap_packages | bool
      tags: ['snap-packages']

    - include_tasks: tasks/ssh.yml
      when: configure_ssh | bool
      tags: ['ssh']

    - include_tasks: tasks/zsh.yml
      when: (configure_zsh and configure_dotfiles) | bool
      tags: ['zsh', 'dotfiles']

    - include_tasks: tasks/extra-packages.yml
      when: configure_extra_packages | bool
      tags: ['extra-packages']

    - include_tasks: tasks/folders.yml
      when: configure_folders | bool
      tags: ['folders']

    - name: Run configured post-provision ansible task files.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"

    - debug: msg="the value of ~/.bashrc is {{lookup('file', '~/.bashrc') }}"
    - debug: msg="the value of ~/.bash_profile is {{lookup('file', '~/.bash_profile') }}"
    - debug: msg="the value of ~/.profile is {{lookup('file', '~/.profile') }}"
    - debug: msg="the value of ~/.zshrc is {{lookup('file', '~/.zshrc') }}"
    - debug: msg="the value of ~/.zprofile is {{lookup('file', '~/.zprofile') }}"
    - debug: msg="the value of ~/.zshrc.local is {{lookup('file', '~/.zshrc.local') }}"
