---
- name: Update repositories if pkg_mgr = apt.
  apt:
    update_cache: yes
  become: yes
  when: ansible_facts['pkg_mgr'] == 'apt'

- name: Install packages.
  package:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ packages }}"
