---
- name: Install snap packages.
  snap:
    name: "{{ item.name | default(item) }}"
    classic: "{{ item.classic | default(yes) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ snap_packages }}"
